package com.rmgYantra.loginapp.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.web.bind.annotation.CrossOrigin;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

@Entity
@Data
public class DemoRequest {
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "demo_seq")
	@GenericGenerator(name = "demo_seq",strategy = "com.rmgYantra.loginapp.model.StringPrefixedSequesceGenerator",
	parameters = {@Parameter(name = StringPrefixedSequesceGenerator.VALUE_PREFIX_PARAMETER, value = "RD_"),
			@Parameter(name = StringPrefixedSequesceGenerator.NUMBER_FORMAT_PARAMETER, value = "%05d"),
			@Parameter(name = StringPrefixedSequesceGenerator.INCREMENT_PARAM, value = "10")})
	@ApiModelProperty(notes = "Employee ID is Auto-generated By the Server,don't ask from user",hidden = true)
	private String requestId;
	private String name;
	private String email;
	private String contact;
	private boolean notify;
}
