package com.rmgYantra.loginapp.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class ProjectModule {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "module_seq")
	@GenericGenerator(name = "module_seq",strategy = "com.rmgYantra.loginapp.model.StringPrefixedSequesceGenerator",
			parameters = {@Parameter(name = StringPrefixedSequesceGenerator.VALUE_PREFIX_PARAMETER, value = "M"),
					@Parameter(name = StringPrefixedSequesceGenerator.NUMBER_FORMAT_PARAMETER, value = "%03d"),
					@Parameter(name = StringPrefixedSequesceGenerator.INCREMENT_PARAM, value = "100")})
			@ApiModelProperty(notes = "ModuleId is Auto-generated By the server,don't use it",hidden = true)
	private String moduleId;
	
	private String moduleName;
	@ApiModelProperty(notes = "CreatedOn is Auto-generated By the server,don't use it",hidden = true)
	private String createdOn;
	
	private String assignedTo;
	
	@ApiModelProperty(notes = "AssignedOn is Auto-generated By the server,don't use it",hidden = true)
	private String assignedOn;
	
	private String status;
	
	private String projectId;
	
	

}
