package com.rmgYantra.loginapp.model;

import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
//import javax.validation.constraints.NotNull;
//import javax.validation.constraints.Pattern;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.lang.Nullable;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor

@Table(name="user")
public class User {
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "user_seq")
	@GenericGenerator(name = "user_seq",strategy = "com.rmgYantra.loginapp.model.StringPrefixedSequesceGenerator",
	parameters = {@Parameter(name = StringPrefixedSequesceGenerator.VALUE_PREFIX_PARAMETER, value = "USER_"),
			@Parameter(name = StringPrefixedSequesceGenerator.NUMBER_FORMAT_PARAMETER, value = "%05d"),
			@Parameter(name = StringPrefixedSequesceGenerator.INCREMENT_PARAM, value = "100")})
	@ApiModelProperty(notes = "Employee ID is Auto-generated By the Server,don't use it",hidden = true)
	private String id;
	//@NotNull
	private String name;
	//@NotNull
	@Column(unique = true)
	private String email;
	//@NotNull
	@Column(unique = true)
	private String username;
	//@NotNull
	private String password;
	//@NotNull
	//@Pattern(regexp="(^$|[0-9]{10})",message = "Enter a valid mobile number")
	@ApiModelProperty(notes = "enter 10 digits mobile number")
	@Column(unique = true)
	private String contact;
	//@NotNull
	private String role; 
	
	private String address;
	private String gender;
	@Nullable
	private Date dob;
	
	
	
	
	
	

}
